development:
  clients:
    default:
      database: archinotesx_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: archinotesx_development
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
